name-template: 'Boxed Templates $RESOLVED_VERSION'
tag-template: 'Boxed.Templates.$RESOLVED_VERSION'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
no-changes-template: '- No changes'
categories:
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '📦 ASP.NET Core API Boxed'
    labels:
      - 'template/API'
  - title: '📦 ASP.NET Core GraphQL Boxed'
    labels:
      - 'template/GraphQL'
  - title: '📦 Microsoft Orleans Boxed'
    labels:
      - 'template/Orleans'
  - title: '📦 Microsoft NuGet Package Boxed'
    labels:
      - 'template/NuGet'
  - title: '📄 Item Templates'
    labels:
      - 'template/Item'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES

  ## 👨🏼‍💻 Contributors

  $CONTRIBUTORS
autolabeler:
  - label: 'documentation'
    files:
      - 'Docs/**/*'
  - label: 'maintenance'
    files:
      - '.github/**/*'
      - 'Docs/**/*'
      - 'Images/**/*'
      - 'Tests/**/*'
  - label: 'template/API'
    files:
      - 'Source/ApiTemplate/**/*'
  - label: 'template/GraphQL'
    files:
      - 'Source/GraphQLTemplate/**/*'
  - label: 'template/NuGet'
    files:
      - 'Source/NuGetTemplate/**/*'
  - label: 'template/Orleans'
    files:
      - 'Source/OrleansTemplate/**/*'
  - label: 'template/Item'
    files:
      - 'Source/EditorconfigTemplate/**/*'
      - 'Source/GitattributesTemplate/**/*'
